<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_X_Error_Message</name>
   <tag></tag>
   <elementGuidId>275a5a16-4da2-4e4c-b4eb-cbe569fdcd6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;container&quot;]/div/div/div[1]/div[2]/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-reactid = '.0.0.0.2.0.1.0.1' and @class = 'close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.2.0.1.0.1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
   </webElementProperties>
</WebElementEntity>
